Attempt at a fix for issue #176
openscopeproject/InteractiveHtmlBom pull request #203
Opened 2020-11-25 04:15 UTC by unsynchronized

When "Darken when checked" is enabled, footprints that match the
criterion chosen (i.e. sourced or placed) are highlighted in a separate
color.  The currently-highlighted footprint is also shown in a third
color if it has met the sourced/placed criterion.

Upstream issue #176.

2020-11-25 06:09 UTC, qu1ck requested changes
Good for a first pass, needs some tweaks.

2020-11-25 06:09 UTC, qu1ck commented on InteractiveHtmlBom/web/render.js
> +          drawFootprint(ctx, layer, scalefactor, mod, padcolor, outlinecolor, highlight, outline);
This now draws a bounding box for every single footprint which is a bug.

In general the whole block has too many nested conditions.

I suggest following: 
* make padcolor and outlinecolor a single object passed into drawFootprint()
* precalculate 4 instances of that object based on style: normal, highlighted, darkened, both.
* write non-nested if () {} else if () {} ... statements that handle each case:
  * non-highlight mode: draw normal
  * highlightedFootprints and darkenedFootprints have the ref: draw with "both" color
  * darkenedFootprints has the ref: draw "darkened"
  * highlightedFootprints has the ref: draw "highlighted"

2020-12-05 14:19 UTC, qu1ck commented
Let me know if you don't plan to address the review comments in, say, next week or two. I will touch this up and merge it.

2020-12-05 19:46 UTC, unsynchronized commented
I will soon -- got busy, sorry!

2020-12-05 22:28 UTC, qu1ck commented
Yeah, no rush, just wanted to know if it's still on your radar.

2021-01-25 20:11 UTC, nopeppermint commented
@unsynchronized any update on this?

2021-07-24 21:19 UTC, closed without merging